Repository aerasproject/core, pull requests merged in 2022-04, with the labels that each got.

#14 Adicionando novos endpoints ao package
  src/Controllers/publicAddress.controller.ts
  src/Controllers/technician.controller.ts
  src/Controllers/user.controller.ts
  src/Types/PublicAddress.ts
  src/Types/Technician.ts
  tsconfig.json
Labels: feat

#16 Criado pasta Enums para: os tipos de servico e tipos de usuários
  src/Enums/CompanyServices.ts
  src/Enums/TechnicianServices.ts
  src/Enums/UserRoles.ts
  src/index.ts
Labels: feat

#17 Ajustado quebra de pipeline para nova versão
  package.json
Labels: bug

#18 Enhancement/atualizando tipo role user com enum
  package.json
  src/Controllers/user.controller.ts
  tsconfig.json
Labels: enhancement

#19 Atualizado Enum de User-Roles
  package.json
  src/Enums/UserRoles.ts
Labels: documentation, enhancement

#20 Atualizado propriedades de IUser
  package.json
  src/Types/User.ts
Labels: feat

#21 Atualizando Enum de Services e v0.0.29
  package.json
  src/Enums/CompanyServices.ts
  src/Enums/TechnicianServices.ts
Labels: enhancement
